LibraryICE/Models/Loan.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryICE.Models
{
    public class Loan
    {
        [Key] public int LoanID { get; set; }
        [Required] public int BookID { get; set; }
        [Required] public DateTime LoanDate { get; set; }
    }
}

LibraryICE/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryICE.Models;

namespace LibraryICE.Controllers
{
    public class LoansController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LoansController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Loans
        public async Task<IActionResult> Index(string bookFilter, string startDate, string endDate)
        {
            // get lists of book and loans to use
            var loans = await _context.Loan.ToListAsync();
            var books = await _context.Book.ToListAsync();

            // we create a new selectlist, pass it to the viewbag, so our dropdownlist can have values
            ViewBag.BookOptions = new SelectList(books, "BookID", "Title");

            // if the user selected a book from the dropdown, check for all loans that are for that book, and return a list
            if (!String.IsNullOrEmpty(bookFilter))
            {
                loans = loans.Where(s => s.BookID.ToString() == bookFilter).ToList();
            }

            // if the user has entered a start AND an end date, then check for all loans that fall between these values
            if (!String.IsNullOrEmpty(startDate) && !String.IsNullOrEmpty(endDate))
            {
                // convert to datetimes instead of strings, because the database stores in a datetime format
                DateTime start = DateTime.Parse(startDate);
                DateTime end = DateTime.Parse(endDate);
                // we use LINQ again, to check if the loan date is smaller than the start date, and bigger than the end date
                loans = loans.Where(s => s.LoanDate >= start && s.LoanDate <= end).ToList();
            }

            return View(loans);
        }

        // GET: Loans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loan
                .FirstOrDefaultAsync(m => m.LoanID == id);
            if (loan == null)
            {
                return NotFound();
            }

            return View(loan);
        }

        // GET: Loans/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Loans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LoanID,BookID,LoanDate")] Loan loan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(loan);
        }

        // GET: Loans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loan.FindAsync(id);
            if (loan == null)
            {
                return NotFound();
            }
            return View(loan);
        }

        // POST: Loans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LoanID,BookID,LoanDate")] Loan loan)
        {
            if (id != loan.LoanID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoanExists(loan.LoanID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loan);
        }

        // GET: Loans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loan
                .FirstOrDefaultAsync(m => m.LoanID == id);
            if (loan == null)
            {
                return NotFound();
            }

            return View(loan);
        }

        // POST: Loans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var loan = await _context.Loan.FindAsync(id);
            if (loan != null)
            {
                _context.Loan.Remove(loan);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoanExists(int id)
        {
            return _context.Loan.Any(e => e.LoanID == id);
        }
    }
}

LibraryICE/Views/Loans/Create.cshtml
@model LibraryICE.Models.Loan

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Loan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookID" class="control-label"></label>
                <input asp-for="BookID" class="form-control" />
                <span asp-validation-for="BookID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoanDate" class="control-label"></label>
                <input asp-for="LoanDate" class="form-control" />
                <span asp-validation-for="LoanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryICE/Views/Loans/Delete.cshtml
@model LibraryICE.Models.Loan

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Loan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LoanID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LibraryICE/Views/Loans/Details.cshtml
@model LibraryICE.Models.Loan

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Loan</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LoanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LoanDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.LoanID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LibraryICE/Views/Loans/Edit.cshtml
@model LibraryICE.Models.Loan

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Loan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LoanID" />
            <div class="form-group">
                <label asp-for="BookID" class="control-label"></label>
                <input asp-for="BookID" class="form-control" />
                <span asp-validation-for="BookID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoanDate" class="control-label"></label>
                <input asp-for="LoanDate" class="form-control" />
                <span asp-validation-for="LoanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryICE/Views/Loans/Index.cshtml
@model IEnumerable<LibraryICE.Models.Loan>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>
@using (Html.BeginForm("Index", "Loans", FormMethod.Get))
{
    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="bookFilter">Search by Book</label>
            @Html.DropDownList("bookFilter", (SelectList)ViewBag.BookOptions, "All Books", new { @class = "form-control" })
        </div>
        <div class="form-group col-md-3">
            <label for="startDate">Start Date+Time</label>
            <input type="datetime-local" class="form-control" id="startDate" name="startDate" value="@ViewBag.StartDate" />
        </div>
        <div class="form-group col-md-3">
            <label for="endDate">End Date+Time</label>
            <input type="datetime-local" class="form-control" id="endDate" name="endDate" value="@ViewBag.EndDate" />
        </div>
        <div class="form-group col-md-3">
            <input type="submit" value="Filter" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-danger">Reset</a>
        </div>
    </div>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LoanDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoanDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LoanID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LoanID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LoanID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>